namespace RecorderCompare
{
    runtimeclass MainViewSku : Microsoft.UI.Xaml.Data.INotifyPropertyChanged
    {
        MainViewSku();
        String LeftLatency;
        String LeftFPS;
        String RightLatency;
        String RightFPS;
    }
}