// Copyright (c) Microsoft Corporation and Contributors.
// Licensed under the MIT License.
import "MainViewModel.idl";

namespace RecorderCompare
{
    [default_interface]
    runtimeclass MainWindow : Microsoft.UI.Xaml.Window
    {
        MainWindow();
        MainViewModel mainViewModel{ get; };
    }
}
